### ISSUE TITLE
Mau buat apa?

### ISSUE THREAD

**Issue by kevanantha** [kevanantha/p0-week1#1]

**Comment by robyafrizal** [comment]
Buat website toko online atau tiketing gt aja gimana?

**Comment by kevanantha** [comment]
Boleh yg lain gmn?

**Comment by RickyDoesCode** [comment]
E-commerce?

**Comment by kevanantha** [comment]
e-commerce nih fix?

**Comment by RickyDoesCode** [comment]
Cuma takutnya terlalu ribet
Page yg perlu dibikin banyak sih

**Comment by RickyDoesCode** [comment]
E-commerce jarang yg cuma beberapa page doang

**Comment by kevanantha** [comment]
Buat landing page company gt gmn? Kyknya lebih gampang

**Comment by robyafrizal** [comment]
Iya sih kayaknya ecommerce itu g bs kalo cuma dibuat dg html dan css..
Aq setuju klo homepage perusahaan/universitas gitu

**Comment by kevanantha** [comment]
@hoandreas @AudrickOng kalian gimana?

**Comment by RickyDoesCode** [comment]
Jd fixed nih webpage perusahaan?

**Comment by RickyDoesCode** [comment]
Gw kemaren ud bikin responsive layout bwt yg personal sih

**Comment by RickyDoesCode** [comment]
Kl mau bwt referebsi sih blh jg

**Comment by kevanantha** [comment]
nanti aja skalian ketemu semuanya omonging, tp boleh juga itu
